### ISSUE TITLE
Not working with Node 0.12

### ISSUE THREAD

**Issue by fenwick67** [koichik/node-tunnel#11]
The `Agent` internal APIs [changed with nodejs 0.12](https://github.com/joyent/node/blob/d13d7f74d794340ac5e126cfb4ce507fe0f803d5/lib/_http_agent.js#L135), so `addRequest` can be called with `(req,options)` instead of `(req,host,port,path)`.  This change causes node-tunnel to break because it doesn't handle this case.

See SalesforceEng/global-tunnel#7

**Comment by koichik** [comment]
Sorry for the long delay, I've published v0.0.4
