### ISSUE TITLE
Using httpOverHttp always?

### ISSUE THREAD

**Issue by rightaway** [koichik/node-tunnel#22]
Maybe I'm not clear on the various functions offered by this module, but I've found it only works for me when I'm using `httpOverHttp`. Whether or not I am connecting to a website that is `http` or `https`, and whether or not I'm using a proxy that is `https` or not (see the `https` column in https://free-proxy-list.net/) - regardless of which of these combinations I'm using, it only ever works with `httpOverHttp`. Is this how it is meant to be or I'm doing something wrong?

**Comment by koichik** [comment]
Sorry for the delay.
`tunnel` supports *[HTTP tunneling proxy](https://en.wikipedia.org/wiki/HTTP_tunnel)* using `CONNECT` method, and most of usecase is `httpsOverHttp`.
Closing.
