### ISSUE TITLE
CONNECT request should use port 443 as default for HTTPS

### ISSUE THREAD

**Issue by mk-pmb** [koichik/node-tunnel#32]
Hi, thanks for this module!

`.httpsOverHttp` works, but only if I explicitly specify the port as 443. Otherwise it asks the proxy to CONNECT to port 80, my proxy does as requested, the SSL greeting goes to target server's port 80 and it replies with 400 Bad Request.

Could you please change the default port to 443 for the `.httpsOver…` methods?

Update: Here's an [example using example.net](https://gist.github.com/mk-pmb/df15de493551a3512bbd0812454b362b), they reply with 501 Not Implemented.
I'm using  tunnel v0.0.5, Node.js v8.11.4, npm v5.6.0, Ubuntu 14.04.5 LTS trusty,

**Comment by ash0080** [comment]
Same issue, besides, there isn‘t an auto routing methods for http & https, super annoying for a hybrid site for example most shopping sites

**Comment by mk-pmb** [comment]
> auto routing methods

Do you mean automatic method selection based on URL? In that case, the [`got` package](https://www.npmjs.com/package/got) got you covered. Its readme's "Proxies" chapter shows how to configure different agents per protocol.

**Comment by ash0080** [comment]
@mk-pmb yes, but node-tunnel doesn't work( cuz the port mistake ) , I am using [proxy-agent](https://www.npmjs.com/package/proxy-agent) for instead now, auto fit http&https

**Comment by koichik** [comment]
Sorry for the delay, thanks!

**Comment by mk-pmb** [comment]
Do you know yet when it will be released?

**Comment by koichik** [comment]
Just published!
