### ISSUE TITLE
socket could not be established using proxy to s3

### ISSUE THREAD

**Issue by allthetime** [koichik/node-tunnel#9]
I am attempting to connect to aws s3 through a proxy and because of issues with authentication am trying to use node-tunnel.

I keep getting `Networking Error: tunneling socket could not be established, cause=bind EADDRNOTAVAIL`

these are my settings:

```
tunnelingAgent = tunnel.httpsOverHttp({
  proxy: {
    host: 'MY_PROXY_SERVER.com'
 }
})

S3.config({
    ...
    httpOptions: { agent: tunnelingAgent }
})
```

am I missing something?

**Comment by koichik** [comment]
If you can provide more information, please reopen this issue.
